export const colors = {
  background: '#FFFFFF',
  card: '#FFFFFF',
  cardBorder: '#D9DDE5',
  text: '#23262D',
  secondary: '#707684',
  dateNumBg: '#DCE0E5',
  dateNumText: '#565B66',
  weekendNumBg: '#FFCDC8',
  weekendNumText: '#B25147',
  activeHeaderBg: '#01B7FF',
  activeCardBorder: '#01B7FF',
  activeHeaderText: '#FFFFFF',
  sundayText: '#FF4B3E',
  sundayNumBg: '#FFF0EE',
  checkboxBorder: '#D7DCE3',
  checkboxBg: '#FFFFFF',
  checkedCheckboxBg: '#C8CED8',
  checkedCheckboxCheck: '#FFFFFF',
  checkedTaskText: '#ADB3BD',
  strikeLine: '#8F97A4',
  inputBg: '#F3F4F6',
  inputBorder: '#E5E8EB',
  inputPlaceholder: '#9AA1AF',
  inputPlusIcon: '#7D8796',
  inputFocusedBorder: '#01B7FF',
  inputEnteredText: '#23262D',
  inputCursor: '#01B7FF',
  divider: '#D9DDE5',
  today: '#01B7FF',
  todayDark: '#0097D4',
  weekend: '#FF4B3E',
  capsule: '#F1F3F6',
  control: '#EDEFF2',
  danger: '#FF4B3E',
} as const;

