export const colors = {
  background: '#FFFFFF',
  card: '#FFFFFF',
  cardBorder: '#D9DDE5',
  text: '#23262D',
  secondary: '#707684',
  dateNumBg: '#F1F3F6',
  dateNumText: '#6D7583',
  activeHeaderBg: '#2F7DF2',
  activeCardBorder: '#2F7DF2',
  activeHeaderText: '#FFFFFF',
  sundayText: '#FF4B3E',
  sundayNumBg: '#FFF0EE',
  checkboxBorder: '#D7DCE3',
  checkboxBg: '#FFFFFF',
  checkedCheckboxBg: '#C8CED8',
  checkedCheckboxCheck: '#FFFFFF',
  checkedTaskText: '#ADB3BD',
  strikeLine: '#8F97A4',
  inputBg: '#FFFFFF',
  inputBorder: '#D9DDE5',
  inputPlaceholder: '#9AA1AF',
  inputPlusIcon: '#7D8796',
  inputFocusedBorder: '#2F7DF2',
  inputEnteredText: '#23262D',
  inputCursor: '#2F7DF2',
  divider: '#D9DDE5',
  today: '#2F7DF2',
  todayDark: '#2164CD',
  weekend: '#FF4B3E',
  capsule: '#F1F3F6',
  control: '#EAEAEE',
  danger: '#FF4B3E',
  time: '#D9FFB6',
} as const;

