import { lightColors, darkColors, type ColorPalette } from './colors';
import type { ThemeId } from '@/types/settings';

export interface ThemeConfig {
  id: ThemeId;
  name: string;
  englishName: string;
  primary: string;
  primaryDark: string;
  background: string;
  tintBg: string;
  activeHeaderText: string;
  today: string;
  todayDark: string;
  activeHeaderBg: string;
  activeCardBorder: string;
  inputFocusedBorder: string;
  inputCursor: string;

  // Hue-harmonized chromatic neutrals
  inputBg: string;
  inputBorder: string;
  cardHeaderBg: string;
  cardBorder: string;
  dateNumBg: string;
  dateNumText: string;
  capsule: string;
  text: string;
  secondary: string;
  inputPlaceholder: string;
  inputPlusIcon: string;
  checkboxBorder: string;
  checkedCheckboxBg: string;
  divider: string;
}

export const THEMES: Record<ThemeId, ThemeConfig> = {
  slate: {
    id: 'slate',
    name: 'Әдепкі',
    englishName: 'Default',
    primary: '#8E8E93',
    primaryDark: '#636366',
    background: '#EFF0F2',
    tintBg: '#F2F2F7',
    activeHeaderText: '#FFFFFF',
    today: '#8E8E93',
    todayDark: '#636366',
    activeHeaderBg: '#8E8E93',
    activeCardBorder: '#8E8E93',
    inputFocusedBorder: '#8E8E93',
    inputCursor: '#8E8E93',
    inputBg: '#F8FAFC',
    inputBorder: '#EDF1F5',
    cardHeaderBg: '#EDEFF2',
    cardBorder: '#D9DDE5',
    dateNumBg: '#DCE0E5',
    dateNumText: '#565B66',
    capsule: '#F1F3F6',
    text: '#31383E',
    secondary: '#707684',
    inputPlaceholder: '#9AA1AF',
    inputPlusIcon: '#8E8E93',
    checkboxBorder: '#D7DCE3',
    checkedCheckboxBg: '#CBD5E1',
    divider: '#D9DDE5',
  },
  ocean: {
    id: 'ocean',
    name: 'Көк',
    englishName: 'Blue',
    primary: '#0195FF',
    primaryDark: '#0080DE',
    background: '#EFF0F2',
    tintBg: '#E6F4FF',
    activeHeaderText: '#FFFFFF',
    today: '#0195FF',
    todayDark: '#0080DE',
    activeHeaderBg: '#0195FF',
    activeCardBorder: '#0195FF',
    inputFocusedBorder: '#0195FF',
    inputCursor: '#0195FF',
    inputBg: '#F8FAFC',
    inputBorder: '#EDF1F5',
    cardHeaderBg: '#EDEFF2',
    cardBorder: '#D9DDE5',
    dateNumBg: '#DCE0E5',
    dateNumText: '#565B66',
    capsule: '#F1F3F6',
    text: '#31383E',
    secondary: '#707684',
    inputPlaceholder: '#9AA1AF',
    inputPlusIcon: '#0195FF',
    checkboxBorder: '#D7DCE3',
    checkedCheckboxBg: '#CBD2D8',
    divider: '#D9DDE5',
  },
  emerald: {
    id: 'emerald',
    name: 'Жасыл',
    englishName: 'Green',
    primary: '#53B55A',
    primaryDark: '#419947',
    background: '#EFF0F2',
    tintBg: '#EDF7EE',
    activeHeaderText: '#FFFFFF',
    today: '#53B55A',
    todayDark: '#419947',
    activeHeaderBg: '#53B55A',
    activeCardBorder: '#53B55A',
    inputFocusedBorder: '#53B55A',
    inputCursor: '#53B55A',
    inputBg: '#F8FAFC',
    inputBorder: '#EDF1F5',
    cardHeaderBg: '#EDEFF2',
    cardBorder: '#D9DDE5',
    dateNumBg: '#DCE0E5',
    dateNumText: '#565B66',
    capsule: '#F1F3F6',
    text: '#31383E',
    secondary: '#707684',
    inputPlaceholder: '#9AA1AF',
    inputPlusIcon: '#53B55A',
    checkboxBorder: '#D7DCE3',
    checkedCheckboxBg: '#BCD5C7',
    divider: '#D9DDE5',
  },
  amber: {
    id: 'amber',
    name: 'Сары',
    englishName: 'Yellow',
    primary: '#F6C543',
    primaryDark: '#DFAB29',
    background: '#EFF0F2',
    tintBg: '#FEF9EB',
    activeHeaderText: '#FFFFFF',
    today: '#F6C543',
    todayDark: '#DFAB29',
    activeHeaderBg: '#F6C543',
    activeCardBorder: '#F6C543',
    inputFocusedBorder: '#F6C543',
    inputCursor: '#F6C543',
    inputBg: '#F8FAFC',
    inputBorder: '#EDF1F5',
    cardHeaderBg: '#EDEFF2',
    cardBorder: '#D9DDE5',
    dateNumBg: '#DCE0E5',
    dateNumText: '#565B66',
    capsule: '#F1F3F6',
    text: '#31383E',
    secondary: '#707684',
    inputPlaceholder: '#9AA1AF',
    inputPlusIcon: '#F6C543',
    checkboxBorder: '#D7DCE3',
    checkedCheckboxBg: '#DCD6CE',
    divider: '#D9DDE5',
  },
  pink: {
    id: 'pink',
    name: 'Қызғылт',
    englishName: 'Pink',
    primary: '#F077AF',
    primaryDark: '#D65D95',
    background: '#EFF0F2',
    tintBg: '#FDF1F6',
    activeHeaderText: '#FFFFFF',
    today: '#F077AF',
    todayDark: '#D65D95',
    activeHeaderBg: '#F077AF',
    activeCardBorder: '#F077AF',
    inputFocusedBorder: '#F077AF',
    inputCursor: '#F077AF',
    inputBg: '#F8FAFC',
    inputBorder: '#EDF1F5',
    cardHeaderBg: '#EDEFF2',
    cardBorder: '#D9DDE5',
    dateNumBg: '#DCE0E5',
    dateNumText: '#565B66',
    capsule: '#F1F3F6',
    text: '#31383E',
    secondary: '#707684',
    inputPlaceholder: '#9AA1AF',
    inputPlusIcon: '#F077AF',
    checkboxBorder: '#D7DCE3',
    checkedCheckboxBg: '#D6C8CF',
    divider: '#D9DDE5',
  },
  coral: {
    id: 'coral',
    name: 'Оранжевый',
    englishName: 'Orange',
    primary: '#EE7C38',
    primaryDark: '#D66624',
    background: '#EFF0F2',
    tintBg: '#FDF2EC',
    activeHeaderText: '#FFFFFF',
    today: '#EE7C38',
    todayDark: '#D66624',
    activeHeaderBg: '#EE7C38',
    activeCardBorder: '#EE7C38',
    inputFocusedBorder: '#EE7C38',
    inputCursor: '#EE7C38',
    inputBg: '#F8FAFC',
    inputBorder: '#EDF1F5',
    cardHeaderBg: '#EDEFF2',
    cardBorder: '#D9DDE5',
    dateNumBg: '#DCE0E5',
    dateNumText: '#565B66',
    capsule: '#F1F3F6',
    text: '#31383E',
    secondary: '#707684',
    inputPlaceholder: '#9AA1AF',
    inputPlusIcon: '#EE7C38',
    checkboxBorder: '#D7DCE3',
    checkedCheckboxBg: '#DFCECD',
    divider: '#D9DDE5',
  },
  violet: {
    id: 'violet',
    name: 'Күлгін',
    englishName: 'Purple',
    primary: '#8A52EE',
    primaryDark: '#723BD6',
    background: '#EFF0F2',
    tintBg: '#F4EEFD',
    activeHeaderText: '#FFFFFF',
    today: '#8A52EE',
    todayDark: '#723BD6',
    activeHeaderBg: '#8A52EE',
    activeCardBorder: '#8A52EE',
    inputFocusedBorder: '#8A52EE',
    inputCursor: '#8A52EE',
    inputBg: '#F8FAFC',
    inputBorder: '#EDF1F5',
    cardHeaderBg: '#EDEFF2',
    cardBorder: '#D9DDE5',
    dateNumBg: '#DCE0E5',
    dateNumText: '#565B66',
    capsule: '#F1F3F6',
    text: '#31383E',
    secondary: '#707684',
    inputPlaceholder: '#9AA1AF',
    inputPlusIcon: '#8A52EE',
    checkboxBorder: '#D7DCE3',
    checkedCheckboxBg: '#D2CBDF',
    divider: '#D9DDE5',
  },
  minimal: {
    id: 'minimal',
    name: 'Қара',
    englishName: 'Black',
    primary: '#000000',
    primaryDark: '#18181B',
    background: '#EFF0F2',
    tintBg: '#F4F4F5',
    activeHeaderText: '#FFFFFF',
    today: '#000000',
    todayDark: '#18181B',
    activeHeaderBg: '#000000',
    activeCardBorder: '#000000',
    inputFocusedBorder: '#000000',
    inputCursor: '#000000',
    inputBg: '#F8FAFC',
    inputBorder: '#EDF1F5',
    cardHeaderBg: '#EDEFF2',
    cardBorder: '#D9DDE5',
    dateNumBg: '#DCE0E5',
    dateNumText: '#565B66',
    capsule: '#F1F3F6',
    text: '#31383E',
    secondary: '#707684',
    inputPlaceholder: '#9AA1AF',
    inputPlusIcon: '#000000',
    checkboxBorder: '#D7DCE3',
    checkedCheckboxBg: '#27272A',
    divider: '#D9DDE5',
  },
  teal: {
    id: 'teal',
    name: 'Көк',
    englishName: 'Blue',
    primary: '#0195FF',
    primaryDark: '#0080DE',
    background: '#EFF0F2',
    tintBg: '#E6F4FF',
    activeHeaderText: '#FFFFFF',
    today: '#0195FF',
    todayDark: '#0080DE',
    activeHeaderBg: '#0195FF',
    activeCardBorder: '#0195FF',
    inputFocusedBorder: '#0195FF',
    inputCursor: '#0195FF',
    inputBg: '#F8FAFC',
    inputBorder: '#EDF1F5',
    cardHeaderBg: '#EDEFF2',
    cardBorder: '#D9DDE5',
    dateNumBg: '#DCE0E5',
    dateNumText: '#565B66',
    capsule: '#F1F3F6',
    text: '#31383E',
    secondary: '#707684',
    inputPlaceholder: '#9AA1AF',
    inputPlusIcon: '#0195FF',
    checkboxBorder: '#D7DCE3',
    checkedCheckboxBg: '#CBD2D8',
    divider: '#D9DDE5',
  },
};

export const THEME_LIST: ThemeConfig[] = [
  THEMES.slate,
  THEMES.ocean,
  THEMES.emerald,
  THEMES.amber,
  THEMES.pink,
  THEMES.coral,
  THEMES.violet,
  THEMES.minimal,
];

export type AppColors = ColorPalette & {
  primary: string;
  primaryDark: string;
  tintBg: string;
};

export function getThemeColors(themeId?: ThemeId, isDark: boolean = false): AppColors {
  const theme = (themeId && THEMES[themeId]) ? THEMES[themeId] : THEMES.ocean;

  if (isDark) {
    if (theme.id === 'minimal') {
      return {
        ...darkColors,
        primary: '#E4E4E7',
        primaryDark: '#D4D4D8',
        today: '#E4E4E7',
        todayDark: '#A1A1AA',
        activeHeaderBg: '#3F485A',
        activeCardBorder: '#A1A1AA',
        activeHeaderText: '#FFFFFF',
        inputFocusedBorder: '#A1A1AA',
        inputCursor: '#E4E4E7',
        inputPlusIcon: '#E4E4E7',
        tintBg: 'rgba(255, 255, 255, 0.08)',
        chipBg: darkColors.inputBg,
        chipBorder: darkColors.inputBorder,
        chipText: darkColors.text,
        chipActiveText: '#FFFFFF',
      };
    }

    if (theme.id === 'slate') {
      return {
        ...darkColors,
        primary: '#94A3B8',
        primaryDark: '#64748B',
        today: '#94A3B8',
        todayDark: '#64748B',
        activeHeaderBg: '#94A3B8',
        activeCardBorder: '#94A3B8',
        activeHeaderText: '#0F172A',
        inputFocusedBorder: '#94A3B8',
        inputCursor: '#94A3B8',
        inputPlusIcon: '#94A3B8',
        tintBg: 'rgba(148, 163, 184, 0.15)',
        chipBg: darkColors.inputBg,
        chipBorder: darkColors.inputBorder,
        chipText: darkColors.text,
        chipActiveText: '#F3F5F9',
      };
    }

    return {
      ...darkColors,
      primary: theme.primary,
      primaryDark: theme.primaryDark,
      tintBg: `${theme.today}1A`,
      today: theme.today,
      todayDark: theme.todayDark,
      activeHeaderBg: theme.today,
      activeCardBorder: theme.today,
      activeHeaderText: '#FFFFFF',
      inputFocusedBorder: theme.today,
      inputCursor: theme.today,
      inputPlusIcon: theme.primary,
      chipBg: darkColors.inputBg,
      chipBorder: darkColors.inputBorder,
      chipText: darkColors.text,
      chipActiveText: '#F3F5F9',
    };
  }

  return {
    ...lightColors,
    primary: theme.primary,
    primaryDark: theme.primaryDark,
    tintBg: theme.tintBg,
    today: theme.today,
    todayDark: theme.todayDark,
    activeHeaderBg: theme.today,
    activeCardBorder: theme.today,
    activeHeaderText: '#FFFFFF',
    inputFocusedBorder: theme.today,
    inputCursor: theme.today,
    inputPlusIcon: theme.primary,
  };
}
