import { colors as baseColors, type ColorPalette } from './colors';
import type { ThemeId } from '@/types/settings';

export interface ThemeConfig {
  id: ThemeId;
  name: string;
  englishName: string;
  primary: string;
  primaryDark: string;
  background: string;
  tintBg: string;
  activeHeaderText: string;
  today: string;
  todayDark: string;
  activeHeaderBg: string;
  activeCardBorder: string;
  inputFocusedBorder: string;
  inputCursor: string;

  // Hue-harmonized chromatic neutrals
  inputBg: string;
  inputBorder: string;
  cardHeaderBg: string;
  cardBorder: string;
  dateNumBg: string;
  dateNumText: string;
  capsule: string;
  text: string;
  secondary: string;
  inputPlaceholder: string;
  inputPlusIcon: string;
  checkboxBorder: string;
  checkedCheckboxBg: string;
  divider: string;
}

export const THEMES: Record<ThemeId, ThemeConfig> = {
  ocean: {
    id: 'ocean',
    name: 'Көк мұхит',
    englishName: 'Ocean Blue',
    primary: '#01B7FF',
    primaryDark: '#009FD6',
    background: '#FAFCFD',
    tintBg: '#EAF8FF',
    activeHeaderText: '#FFFFFF',
    today: '#01B7FF',
    todayDark: '#009FD6',
    activeHeaderBg: '#01B7FF',
    activeCardBorder: '#01B7FF',
    inputFocusedBorder: '#01B7FF',
    inputCursor: '#01B7FF',
    inputBg: '#F6F8FA',
    inputBorder: '#E5E9ED',
    cardHeaderBg: '#EDEFF2',
    cardBorder: '#E1E5E9',
    dateNumBg: '#DFE4E8',
    dateNumText: '#455562',
    capsule: '#F6F8FA',
    text: '#1C242B',
    secondary: '#5D6B75',
    inputPlaceholder: '#8B97A0',
    inputPlusIcon: '#5D6B75',
    checkboxBorder: '#D0D7DC',
    checkedCheckboxBg: '#CBD2D8',
    divider: '#E5E9ED',
  },
  pink: {
    id: 'pink',
    name: 'Қызғылт',
    englishName: 'Soft Pink',
    primary: '#FF87C4',
    primaryDark: '#E66FA9',
    background: '#FFFAFD',
    tintBg: '#FFF0F7',
    activeHeaderText: '#FFFFFF',
    today: '#FF87C4',
    todayDark: '#E66FA9',
    activeHeaderBg: '#FF87C4',
    activeCardBorder: '#FF87C4',
    inputFocusedBorder: '#FF87C4',
    inputCursor: '#FF87C4',
    inputBg: '#FAF6F8',
    inputBorder: '#EFE6EB',
    cardHeaderBg: '#F3EBEE',
    cardBorder: '#EAE0E5',
    dateNumBg: '#ECE0E6',
    dateNumText: '#6B4557',
    capsule: '#FAF6F8',
    text: '#2B1C23',
    secondary: '#755463',
    inputPlaceholder: '#A58795',
    inputPlusIcon: '#755463',
    checkboxBorder: '#DCD0D6',
    checkedCheckboxBg: '#D6C8CF',
    divider: '#EFE6EB',
  },
  violet: {
    id: 'violet',
    name: 'Күлгін ғарыш',
    englishName: 'Royal Violet',
    primary: '#906AF4',
    primaryDark: '#7C54E0',
    background: '#FCFBFE',
    tintBg: '#F5F2FE',
    activeHeaderText: '#FFFFFF',
    today: '#906AF4',
    todayDark: '#7C54E0',
    activeHeaderBg: '#906AF4',
    activeCardBorder: '#906AF4',
    inputFocusedBorder: '#906AF4',
    inputCursor: '#906AF4',
    inputBg: '#F8F7FB',
    inputBorder: '#ECE8F3',
    cardHeaderBg: '#F1EEF5',
    cardBorder: '#E7E3EE',
    dateNumBg: '#E7E2F0',
    dateNumText: '#554877',
    capsule: '#F8F7FB',
    text: '#251F33',
    secondary: '#6A5E82',
    inputPlaceholder: '#9E94B5',
    inputPlusIcon: '#6A5E82',
    checkboxBorder: '#D8D2E6',
    checkedCheckboxBg: '#D2CBDF',
    divider: '#ECE8F3',
  },
  teal: {
    id: 'teal',
    name: 'Теңіз толқыны',
    englishName: 'Teal Green',
    primary: '#009096',
    primaryDark: '#007A80',
    background: '#FAFCFC',
    tintBg: '#E6F7F7',
    activeHeaderText: '#FFFFFF',
    today: '#009096',
    todayDark: '#007A80',
    activeHeaderBg: '#009096',
    activeCardBorder: '#009096',
    inputFocusedBorder: '#009096',
    inputCursor: '#009096',
    inputBg: '#F5F9F9',
    inputBorder: '#E3EDED',
    cardHeaderBg: '#ECF2F2',
    cardBorder: '#E0E9E9',
    dateNumBg: '#DEE9E9',
    dateNumText: '#36595B',
    capsule: '#F5F9F9',
    text: '#1A292A',
    secondary: '#526E70',
    inputPlaceholder: '#87A3A5',
    inputPlusIcon: '#526E70',
    checkboxBorder: '#CFDDDD',
    checkedCheckboxBg: '#C7D6D6',
    divider: '#E3EDED',
  },
  amber: {
    id: 'amber',
    name: 'Жылы кәріптас',
    englishName: 'Warm Amber',
    primary: '#FFAA01',
    primaryDark: '#E69900',
    background: '#FFFEFA',
    tintBg: '#FFF8E1',
    activeHeaderText: '#FFFFFF',
    today: '#FFAA01',
    todayDark: '#E69900',
    activeHeaderBg: '#FFAA01',
    activeCardBorder: '#FFAA01',
    inputFocusedBorder: '#FFAA01',
    inputCursor: '#FFAA01',
    inputBg: '#FAF8F5',
    inputBorder: '#EFECE6',
    cardHeaderBg: '#F2F0ED',
    cardBorder: '#EAE6DF',
    dateNumBg: '#EAE5DE',
    dateNumText: '#6E5A44',
    capsule: '#FAF8F5',
    text: '#2B251E',
    secondary: '#7A6E60',
    inputPlaceholder: '#A89D8F',
    inputPlusIcon: '#7A6E60',
    checkboxBorder: '#DCD6CE',
    checkedCheckboxBg: '#DCD6CE',
    divider: '#EFECE6',
  },
  emerald: {
    id: 'emerald',
    name: 'Изумруд',
    englishName: 'Emerald Green',
    primary: '#00A15F',
    primaryDark: '#008A52',
    background: '#FAFCFA',
    tintBg: '#E6F7EE',
    activeHeaderText: '#FFFFFF',
    today: '#00A15F',
    todayDark: '#008A52',
    activeHeaderBg: '#00A15F',
    activeCardBorder: '#00A15F',
    inputFocusedBorder: '#00A15F',
    inputCursor: '#00A15F',
    inputBg: '#F5F9F7',
    inputBorder: '#E3EDE7',
    cardHeaderBg: '#ECF3EF',
    cardBorder: '#E0EAE4',
    dateNumBg: '#DEEAE2',
    dateNumText: '#355E4C',
    capsule: '#F5F9F7',
    text: '#1A2A22',
    secondary: '#527163',
    inputPlaceholder: '#88A397',
    inputPlusIcon: '#527163',
    checkboxBorder: '#CFDED5',
    checkedCheckboxBg: '#C7D8CD',
    divider: '#E3EDE7',
  },
  coral: {
    id: 'coral',
    name: 'Күн шуағы',
    englishName: 'Sunset Coral',
    primary: '#FF6B4A',
    primaryDark: '#E8502C',
    background: '#FEFBFA',
    tintBg: '#FFF3F0',
    activeHeaderText: '#FFFFFF',
    today: '#FF6B4A',
    todayDark: '#E8502C',
    activeHeaderBg: '#FF6B4A',
    activeCardBorder: '#FF6B4A',
    inputFocusedBorder: '#FF6B4A',
    inputCursor: '#FF6B4A',
    inputBg: '#FAF6F6',
    inputBorder: '#EFE6E5',
    cardHeaderBg: '#F4EFEF',
    cardBorder: '#EBE2E1',
    dateNumBg: '#EEDFE0',
    dateNumText: '#754845',
    capsule: '#FAF6F6',
    text: '#311F1F',
    secondary: '#7D5F5E',
    inputPlaceholder: '#B09594',
    inputPlusIcon: '#7D5F5E',
    checkboxBorder: '#E3D4D3',
    checkedCheckboxBg: '#DFCECD',
    divider: '#EFE6E5',
  },
  slate: {
    id: 'slate',
    name: 'Графит',
    englishName: 'Slate Grey',
    primary: '#475569',
    primaryDark: '#334155',
    background: '#FAFAFB',
    tintBg: '#F1F5F9',
    activeHeaderText: '#FFFFFF',
    today: '#475569',
    todayDark: '#334155',
    activeHeaderBg: '#475569',
    activeCardBorder: '#475569',
    inputFocusedBorder: '#475569',
    inputCursor: '#475569',
    inputBg: '#F8FAFB',
    inputBorder: '#E8ECEF',
    cardHeaderBg: '#EFF1F3',
    cardBorder: '#E4E7EA',
    dateNumBg: '#E2E6EB',
    dateNumText: '#475569',
    capsule: '#F8FAFB',
    text: '#1E293B',
    secondary: '#64748B',
    inputPlaceholder: '#94A3B8',
    inputPlusIcon: '#64748B',
    checkboxBorder: '#D0D7DC',
    checkedCheckboxBg: '#CBD5E1',
    divider: '#E8ECEF',
  },
};

export const THEME_LIST: ThemeConfig[] = Object.values(THEMES);

export type AppColors = ColorPalette & {
  primary: string;
  primaryDark: string;
  tintBg: string;
};

export function getThemeColors(themeId?: ThemeId): AppColors {
  const theme = (themeId && THEMES[themeId]) ? THEMES[themeId] : THEMES.ocean;
  return {
    ...baseColors,
    background: theme.background,
    primary: theme.primary,
    primaryDark: theme.primaryDark,
    tintBg: theme.tintBg,
    today: theme.today,
    todayDark: theme.todayDark,
    activeHeaderBg: theme.activeHeaderBg,
    activeCardBorder: theme.activeCardBorder,
    activeHeaderText: theme.activeHeaderText,
    inputFocusedBorder: theme.inputFocusedBorder,
    inputCursor: theme.inputCursor,

    // Hue-harmonized chromatic neutrals
    inputBg: theme.inputBg,
    inputBorder: theme.inputBorder,
    cardHeaderBg: theme.cardHeaderBg,
    cardBorder: theme.cardBorder,
    dateNumBg: theme.dateNumBg,
    dateNumText: theme.dateNumText,
    capsule: theme.capsule,
    text: theme.text,
    secondary: theme.secondary,
    inputPlaceholder: theme.inputPlaceholder,
    inputPlusIcon: theme.inputPlusIcon,
    checkboxBorder: theme.checkboxBorder,
    checkedCheckboxBg: theme.checkedCheckboxBg,
    divider: theme.divider,
  };
}
